backend:
  name: github
  repo: mdesantis/playbook # Path to your GitHub
  branch: middleman # Branch to update (optional; defaults to master) repository
  # name: test-repo

publish_mode: editorial_workflow

media_folder: source/images/uploads
public_folder: /images/uploads

collections:
  - label: Playbook pages
    name: playbook-pages
    folder: source/playbook/
    extension: .html.md
    format: frontmatter
    create: true
    slug: '{{title}}'
    fields:
      - label: Title
        name: title
        widget: string
        required: true
      - label: Body
        name: body
        widget: markdown
